swagger: '2.0'
info:
  title: Athanor test API
  description: Sample API on API Gateway with a Google Cloud Functions backend
  version: 1.0.0
schemes:
  - https
produces:
  - application/json
paths:
  /hello:
    get:
      summary: Greet a user
      operationId: hello
      x-google-backend:
        address: https://us-east4-textapp-389501.cloudfunctions.net/athanor-test-function
      responses:
        '200':
          description: A successful response
          schema:
            type: string
