version: 1

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    main: ./cmd/translator
    binary: translator
    goos:
      - linux
      - darwin

archives:
  - format: tar.gz
    name_template: {{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksum.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

